include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ScreenOffTimeFacebookWatch

ScreenOffTimeFacebookWatch_FILES = Tweak.xm
ScreenOffTimeFacebookWatch_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
