include $(THEOS)/makefiles/common.mk

TWEAK_NAME = ScreenOffTimeScreenTimeButton

ScreenOffTimeScreenTimeButton_FILES = Tweak.x
ScreenOffTimeScreenTimeButton_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
